title: CSP.guru
email: richard.thonig@usys.ethz.ch
description: >-
  This site provides and visualises the CSP.guru dataset of concentrated solar power plants.
url: "https://csp.guru/"
github_username:  repolicy

data_dir: csp-guru
markdown: kramdown
theme: minima
header_pages:
    - data.md
    - about.md
page_gen:
  - index_files: false
    data: csp-guru-2016-08-30
    template: plant
    dir: plant
    name: Title
