title: CSP.guru
author: Energy Transition Dynamics group, IASS Potsdam
email: richard.thonig@iass-potsdam.de
description: >-
  This site provides the CSP.guru dataset of concentrating solar power plants.
url: "https://csp.guru/"
github_username:  repolicy

data_dir: csp-guru
markdown: kramdown
theme: minima
header_pages:
    - data.md
    - metadata.md
    - about.md
