name: Datapackage
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    frictionless:
        name: Frictionless
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install frictionless
            - run: frictionless validate csp-guru/datapackage.json
